kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook
  labels:
    app: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: samplejavaapp
        image: adarshadhal/pythonapp:ad-v1
        ports:
        - name: http
          containerPort: 8080

