kind: Deployment
apiVersion: apps/v1
metadata:
  name: firstweb-application
  labels:
    app: firstweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstweb
  template:
    metadata:
      labels:
        app: firstweb
    spec:
      containers:
      - name: firstweb
        image: adarshadhal/firstweb
        ports:
        - name: http
          containerPort: 8082

